spring:
  application:
    name: rto

  profiles:
    default: local

  datasource:
    url:
    username:
    password:

  flyway:
    enabled: false
    clean-disabled: true
    user:
    password:

  web:
    resources:
      static-locations: file:${rto.storage.root}

  mvc:
    static-path-pattern: /attachments/**

rto:
  storage:
    root:
    server: